### ISSUE TITLE
Second value EasyTimer error

### ISSUE THREAD

**Issue by Yagu-znal** [dpoulson/EPSolar#5]
Hey @dpoulson!
Thanks for the great work. I'm trying to compile the code but it gets stuck on the second value in the easytimer calls in your void function. Claims there is nowhere for the second value to go in the easytimer function. 

> Arduino: 1.8.12 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), 2, v2 Lower Memory, Disabled, None, Only Sketch, 115200"
E:\Downloads\EPSolar-master\EPSolar\EPSolar.ino: In function 'void setup()':
EPSolar:111:57: error: no matching function for call to 'SimpleTimer::setInterval(int, void (&)())'
   timerTask2 = timer.setInterval(10000, doRegistryNumber);
C:\Users\*********\Documents\Arduino\libraries\SimpleTimer/SimpleTimer.h:23:10: note:   candidate expects 1 argument, 2 provided

I did not see any edits on the simpletimer library after publishing so I can't download a previous version. 

I know it's been 2 years but I'd love to use your project in automating my caravan.
Kind regards.

**Comment by hummergobbe** [comment]
Hi,
I'm a long time user of @dpoulson's great work, and recently I helped a friend and compiled and flashed a wemos mini with this code, I got stuck at the same problem initially, and that puzzled me a bit since I had not problems compiling a couple years ago.

The problem was, wrong version of SimpleTimer library installed.
Apparently there are two different versions avaliable.
The one that works for me is: http://playground.arduino.cc/Code/SimpleTimer
Author: mromani@ottotecnica.com

So, uninstall any other version in the arduino ide, and install the above one, and you should be good to go.

**Comment by Yagu-znal** [comment]
Waw thank you for your fast response @hummergobbe . It just compiled with the other library. I would have never found this without you. <3

**Comment by dpoulson** [comment]
Cheers @hummergobbe
